version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'user'
      MYSQL_ROOT_PASSWORD: '123'